changelog:
  categories:
    - title: Features
      labels: [enhancement]
    - title: Fixes
      labels: [bug]
    - title: Documentation and tooling
      labels: [documentation, dependencies]
    - title: Other changes
      labels: ["*"]

